### ISSUE TITLE
RangeError if VC verification fails

### ISSUE THREAD

**Issue by swatigoel** [digitalcredentials/vc#17]
Hi,
We are using this library with version `^1.1.2`.
We are getting an error while verifying the VC.

Response we get after verification is
```
 {
    "verified": false,
    "result": {
        "error": {
            "name": "VerificationError"
        }
    },
    "error": {
        "errors": [
            {
                "name": "RangeError",
                "message": "Maximum call stack size exceeded (native stack depth)"
            }
        ]
    }
 }
```

 After debugging, we could find that, in this file `@digitalcredentials/jsonld/lib/jsonld.js` canonize is being imported `@digitalcredentials/rdf-canonize`. In this library, we could see recursive call is happening for canonize method.

 Because of this, we are unable to identify exact reasoning for verification failure.

 Would be good if someone can help us here?

 Thank You !!

**Comment by kayaelle** [comment]
@swatigoel - thanks for contacting us about this. Our team is looking into it. Stay tuned.

**Comment by swatigoel** [comment]
Hi @kayaelle @dmitrizagidulin 
Do we have any ETA on this?

**Comment by swatigoel** [comment]
@kayaelle We have written a js library to verify VC independently. With this library we are able to verify all VCs even the one which were failing earlier. 
Here is the link for library https://github.com/tw-mosip/verify-credential-js/tree/xhr-movement

We integrated this library in our Application but got same RangeError. 

Is it related to react native framework we are using to build our Application? 🤔 
Sharing this here, if it can help to narrow down the issue.

**Comment by alexfigtree** [comment]
@swatigoel Thank you for this information, we have added this issue to our backlog.

**Comment by alexfigtree** [comment]
@swatigoel We've upgraded to latest versions of DB libraries, so possible that this has already been fixed. Let us know if it's still a blocker for you.

**Comment by alexfigtree** [comment]
11/21/24: Seem to no longer be an issue; closing but can reopen if necessary. @swatigoel If still an issue, let us know.
